export const FETCH_USERS = 'FETCH_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';

export const FETCH_LOCATION = 'FETCH_LOCATION';
export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';

export const FETCH_STATIONS= 'FETCH_STATIONS';
export const RECEIVE_STATIONS = 'RECEIVE_STATIONS';